### ISSUE TITLE
Handling types that implement Display trait

### ISSUE THREAD

**Issue by Steve-Z** [joelparkerhenderson/demo-rust-axum#12]
In the Extractors section I noticed that some code uses `{:?}` when unnecessary, eg, `{}` works fine in these cases:

```
...
format!("Get items with path id: {}", id)
...
format!("Put demo JSON data: {}", data)
```
It only seems to make a difference in the last example, where, with my suggestion to use `{}`, the call returns
`Put demo JSON data: {"a":"b"}`
which is bit clearer than 
`Put demo JSON data: Object({"a": String("b")})`

I realize this is a small point, but as a newbie, it is helpful to learn when to use `{}` vs `{:?}` and how they are different.

**Comment by joelparkerhenderson** [comment]
Yes you're right.

* `{}` means print via `Display`
* `{:?}` means print via `Debug`.
* `{:#?}` means pretty-print via `Debug`.

As a general rule of thumb:

* If the output is intended for an end user, then prefer `{}`.
* If the output is intended for a developer who's reading the code, then prefer `{:?}` because it gives good debugging information. 
* If the debug output is long or complex, then prefer `{:#?}` because it's helpful for developers who use terminals.

**Comment by Steve-Z** [comment]
Thank you for the explanation.
