### ISSUE TITLE
Clippy linting suggests avoiding format!(...).collect()

### ISSUE THREAD

**Issue by Steve-Z** [joelparkerhenderson/demo-rust-axum#14]
Clippy flagged the `get_books()` handler based on this:
https://rust-lang.github.io/rust-clippy/master/index.html#/format_collect
It suggests using fold method. This seems to work:
```
use std::fmt::Write;
pub async fn get_books() -> Html<String> {
    thread::spawn(move || {
        let data = DATA.lock().unwrap();
        let mut books = data.values().collect::<Vec<_>>().clone();
        books.sort_by(|a, b| a.title.cmp(&b.title));
        books.iter().fold(String::new(), |mut output, book| {
            let _ = writeln!(output, "<p>{book}</p>");
            output
        })
    }).join().unwrap().into()
}
```

**Comment by joelparkerhenderson** [comment]
Clippy is mixing together a bunch of sort-of correct practices, for the sake of speed.

In general, going from iterator to map to collect is a design pattern, known as map-reduce. The pattern tends to be easy to understand and debug, because only one item changes at a time, and each item is independent. For comparison, fold uses a aggregation pattern, where the accumulator changes each time through the loop, thus must be mutable, and must be shared state in every loop.

Clippy is optimizing for speed, rather than immutability. And Clippy is doing it by ignoring the result of the writeln macro, which Clippy happens to know shouldn't ever fail-- that's a semantically broken part of the Rust library, btw, to have a Result that can never fail, but can't be omitted syntactically.

When the Rust compiler improves, the immutable loop will become the same speed as the accumulator loop, because the compiler will learn to recognize that a list of immutable strings followed by a collect call is the same thing as a string builder.

IMHO, real world good code looks more like this:

```
books.par_sort_iter(…).map_reduce_string(
    format!("<p>{book}</p>");
})
```

Rust can't quite do that on its own. When I write real world apps, I strongly favor code that reads as functional, immutable, parallelizable, and map-reduce friendly. Rare exceptions are in very hot loops, which could in fact include this one example; I would use cargo bench to compare the two implementations. (And I've done this in practice, and using fold this way is 2x speed, which is a big boost).

Does all of this make sense to you? I can explain more if you want. Essentially I favor writing semantic easy to read code, rather than speed optimized code, until after profiling.

> use std::fmt::Write;
> pub async fn get_books() -> Html<String> {
>     thread::spawn(move || {
>         let data = DATA.lock().unwrap();
>         let mut books = data.values().collect::<Vec<_>>().clone();
>         books.sort_by(|a, b| a.title.cmp(&b.title));
>         books.iter().fold(String::new(), |mut output, book| {
>             let _ = writeln!(output, "<p>{book}</p>");
>             output
>         })
>     }).join().unwrap().into()
> }

**Comment by Steve-Z** [comment]
Thanks for that thorough explanation and for your patience. As is obvious, I am new to rust and to coding. It is a hobby I picked up when I retired from clinical medicine in 2015. Like many, I started with Python. I wrote a couple of humble web apps with Flask. I just began learning rust less than a year ago. Given my lack of experience and minimal education, my approach has been practical -- how do I do X? This sometimes circumvents my understanding of what goes on "under the hood", so to speak. One of the things I like about Rust is that it forces me to understand things at a somewhat deeper level (eg, ownership, mutability). Another thing I like is the direction I get from compiler errors and from Clippy.

I think I do understand what you are saying, at least in a general sense. I just figured that Clippy always knows best which apparently may not be so black-and-white. I appreciate you pointing that out. However, since I am a newbie Rust coder, do you think it is good practice for me to follow Clippy's advice, at least when there is not an experienced coder to point out the nuance?

When I read the Clippy Lints link above
> Note also that write!-ing into a String can never fail, despite the return type of write! being std::fmt::Result, so it can be safely ignored or unwrapped.

I assumed/misinterpreted that was a good thing, but apparently that is not good (which makes sense now that I think about it). As you note above:
> that's a semantically broken part of the Rust library, btw, to have a Result that can never fail, but can't be omitted syntactically.

Can you explain what you mean by "can't be omitted syntactically"? Also I do not understand the term "map-reduce friendly". I did search the std lib and found this: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.reduce
> The reducing function is a closure with two arguments: an ‘accumulator’, and an element. For iterators with at least one element, this is the same as [fold()](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.fold) with the first element of the iterator as the initial accumulator value, folding every subsequent element into it.

I think I understand that. Are you saying you prefer code that is more explicit?

**Comment by joelparkerhenderson** [comment]
Sure happy to help.

> Clippy always knows best

Clippy is great for learning. When it suggests something, it's often a way to learn about deeper aspects of Rust and programming in general.

> write!-ing into a String can never fail, despite the return type of write! being std::fmt::Result

Yep that's bad, in a semantic sense.

> Can you explain what you mean by "can't be omitted syntactically"

The Clippy code is forced to say `let _` to ignore the result. What would be better is code that says something like `x.append(y)` or `x.concat(y)` etc. Rust string handling is more complex than many languages because Rust is very specific about read vs write, and owner vs borrow.

>  I do not understand the term "map-reduce friendly"

https://en.wikipedia.org/wiki/MapReduce

Here's an example of the same kind of function, implemented with the rayon crate, a parallel map stage, and a parallel reduce stage:

```rust
use rayon::prelude::*;

#[inline]
pub fn parallel_map_reduce(items: &Vec<String>) -> String {
    items.par_iter().map(|item|
        format!("<p>{}</p>\n", &item)
    ).reduce(||
        String::new(),
        |a, b| [a, b].concat()
    )
}
```

> Are you saying you prefer code that is more explicit?

Yes for demos, tutorials, introductions, trainings, areas that need auditing/testing/logging/debugging, etc.

Converting from a map-reduce implementation to a left-fold implementation is a typical optimization step, and generally easy to try. (And ideally will eventually be implemented by the Rust compiler getting smarter).
